### PR TITLE
replace SNNSynopCounter with SNNAnalyzer, which calculates statistics for both param and spiking layers

### PR DESCRIPTION
**Pull request by biphasic**
I created SNNAnalyzer to help streamline logging model statistics and calculate additonal objective function terms such as number of synaptic operations. A lot of the time, people do not know how to track firing rates or synaptic operations for different layers in their model or they use their custom code. Using this class, they can simply attach an analyser to their model, which we can then use across the whole team. If users need additional statistics, it's easy to add them here.

### CODE REVIEW

**Comment by bauerfe** [comment]
Looks good to me! I also like that you added unit tests to make sure the expected statistics are obtained.

One thing that confuses me in the ANN tutorial (Training ANNs with fewer Synops) is that it seems to get a non-integer number for the synop count. How can this be when the output of the neuromorphic ReLUs is discrete?

Also, the heading promises more than there actually is. I would have assumed it shows how the ANN can be optimized to reduce the number of synops, but it is only showing how to count them.

This is just a detail, but in the SNN tutorial, the class is called `SNNAnalyzer` with a z, but the instance `analyser`, with an s. Can we stay consistent and stick with one spelling?

**Comment by bauerfe** [comment]
To summarize my (minor) suggestions for improvements:
### ANN tutorial
- [ ] Clarify why there are non-integer synops counts for discrete neuromorphic ReLU
- [ ] Match heading with content
### SNN tutorial
- [ ] Consistent spelling `analyzer` vs `analyser`
### Documentation
- [ ] Mention that synops counts are approximate at the edge of layers (see my comment to `synopcounter.py`

**Comment by biphasic** [comment]
This is now updated! I'm not sure about the last point you listed. Where is that comment?

**Comment by biphasic** [comment]
Also I didn't clarify but the non-integer synops values occured because they are averaged across the batch size. Now feeding a single sample and they're integer as expected :)

**Comment by bauerfe** [comment]
Sorry, I didn't realize I had to publish my review first :sweat_smile: 


> Also I didn't clarify but the non-integer synops values occured because they are averaged across the batch size. Now feeding a single sample and they're integer as expected :)

Ah yes, this is much better now. However, I wonder if we shouldn't point out somewhere that it averages over the batch size. I see how that makes sense, but I hadn't considered or expected that.

Also, wouldn't it make sense to then average over timesteps as well?

**Comment by bauerfe** [comment]
Okay, with the latest changes (transposed convolution for determining fanout), I would suggest these final improvements:

- [ ] Clarify in docs that synops are averaged over batches
- [ ] Clarify (for developers) why taking the transpose convolution gives the fanout. Is there any resource that you could link to?
- [ ] Add some clarifying comments about the `scale_factor` business in `SNNAnalyzer.get_layer_statistics`. It's clever, but I didn't find it completely obvious at first.

**Comment by bauerfe** [comment]
Thanks! I added a little bit more clarification as to why the scaling factors are necessary.

**Pull request merged**
